"""Single-source-of-truth version sync/check for release packaging.

`pyproject.toml`'s `[project].version` is the one authoritative version
string for the whole product. This script derives the two other release
surfaces that must always agree with it -- `packaging/version_info.txt`
(the PyInstaller Windows version resource) and `packaging/installer.iss`'s
`MyAppVersion` preprocessor define -- from that single value, so nobody has
to remember to hand-edit three literals in sync.

Usage:
    python scripts/release_version.py --check   # CI gate: fail if any
                                                  # derived file has drifted
                                                  # from pyproject.toml
    python scripts/release_version.py --write    # regenerate the derived
                                                  # files in place (run this
                                                  # locally after bumping
                                                  # pyproject.toml's version)

`--check` is exactly "regenerate in memory, diff against what's on disk" --
there is no separate hand-maintained consistency rule to fall out of sync
with the generator itself.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PYPROJECT_PATH = REPO_ROOT / "pyproject.toml"
VERSION_INFO_PATH = REPO_ROOT / "packaging" / "version_info.txt"
INSTALLER_ISS_PATH = REPO_ROOT / "packaging" / "installer.iss"

_PYPROJECT_VERSION_RE = re.compile(r'(?m)^version\s*=\s*"([^"]+)"\s*$')
_ISS_VERSION_DEFINE_RE = re.compile(r'(?m)^(#define MyAppVersion ")[^"]+(")\s*$')


class VersionSyncError(RuntimeError):
    pass


def read_product_version() -> str:
    text = PYPROJECT_PATH.read_text(encoding="utf-8")
    match = _PYPROJECT_VERSION_RE.search(text)
    if not match:
        raise VersionSyncError(f"Could not find `version = \"...\"` under [project] in {PYPROJECT_PATH}")
    return match.group(1)


def _four_part(version: str) -> tuple[int, int, int, int]:
    """Windows version resources require exactly four integers
    (major.minor.patch.0); the product version is three-part semver."""
    parts = version.split(".")
    if len(parts) != 3 or not all(part.isdigit() for part in parts):
        raise VersionSyncError(f"Expected a three-part numeric version (e.g. 1.0.0), got {version!r}")
    major, minor, patch = (int(part) for part in parts)
    return major, minor, patch, 0


def render_version_info_txt(version: str) -> str:
    major, minor, patch, build = _four_part(version)
    four_part = f"{major}, {minor}, {patch}, {build}"
    dotted = f"{major}.{minor}.{patch}.{build}"
    return f"""# UTF-8
#
# Windows version resource for the ListenTrace executable (PyInstaller
# `--version-file`). Generated by `scripts/release_version.py` from
# `pyproject.toml`'s `[project].version` -- do not hand-edit the version
# fields below; run `python scripts/release_version.py --write` after
# changing `pyproject.toml` instead.
#
# CompanyName is deliberately just "ListenTrace" (no separate publisher/
# company name) -- see ROADMAP.md's Phase A decisions.

VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({four_part}),
    prodvers=({four_part}),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          u'040904B0',
          [
            StringStruct(u'CompanyName', u'ListenTrace'),
            StringStruct(u'FileDescription', u'ListenTrace'),
            StringStruct(u'FileVersion', u'{dotted}'),
            StringStruct(u'InternalName', u'ListenTrace'),
            StringStruct(u'OriginalFilename', u'ListenTrace.exe'),
            StringStruct(u'ProductName', u'ListenTrace'),
            StringStruct(u'ProductVersion', u'{dotted}'),
          ],
        )
      ]
    ),
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])]),
  ],
)
"""


def render_installer_iss(version: str, current_text: str) -> str:
    new_text, count = _ISS_VERSION_DEFINE_RE.subn(rf"\g<1>{version}\g<2>", current_text)
    if count != 1:
        raise VersionSyncError(
            f'Expected exactly one `#define MyAppVersion "..."` line in {INSTALLER_ISS_PATH}, found {count}'
        )
    return new_text


def check(version: str) -> list[str]:
    problems = []

    expected_version_info = render_version_info_txt(version)
    actual_version_info = VERSION_INFO_PATH.read_text(encoding="utf-8")
    if actual_version_info != expected_version_info:
        problems.append(f"{VERSION_INFO_PATH} is out of sync with pyproject.toml version {version!r}")

    current_iss = INSTALLER_ISS_PATH.read_text(encoding="utf-8")
    expected_iss = render_installer_iss(version, current_iss)
    if current_iss != expected_iss:
        problems.append(f"{INSTALLER_ISS_PATH} is out of sync with pyproject.toml version {version!r}")

    return problems


def write(version: str) -> None:
    VERSION_INFO_PATH.write_text(render_version_info_txt(version), encoding="utf-8")
    current_iss = INSTALLER_ISS_PATH.read_text(encoding="utf-8")
    INSTALLER_ISS_PATH.write_text(render_installer_iss(version, current_iss), encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true", help="fail if derived files have drifted (CI gate)")
    mode.add_argument("--write", action="store_true", help="regenerate derived files in place")
    args = parser.parse_args(argv)

    try:
        version = read_product_version()
    except VersionSyncError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    if args.write:
        write(version)
        print(f"Synced packaging/version_info.txt and packaging/installer.iss to version {version}")
        return 0

    problems = check(version)
    if problems:
        for problem in problems:
            print(f"error: {problem}", file=sys.stderr)
        print("Run `python scripts/release_version.py --write` to fix.", file=sys.stderr)
        return 1

    print(f"packaging/version_info.txt and packaging/installer.iss match pyproject.toml version {version}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
